-- =========================================================
-- BakeryOS Production DB Hardening Execution Guide
-- =========================================================
-- Files were split so each script stays <= 100 lines.
-- Apply after base schema scripts:
--   1) production_hardening_constraints_orders.sql
--   2) production_hardening_constraints_finance.sql
--   3) production_hardening_policy_setup.sql
--   4) production_hardening_policy_orders_showcase.sql
--   5) production_hardening_policy_finance.sql
--   6) production_auth_staff_binding.sql
--   7) production_auth_staff_unlink.sql
--   8) production_auth_staff_audit_view.sql
--   9) production_auth_staff_reporting.sql
