-- =========================================================
-- BakeryOS Production: Auth User <-> Staff Binding
-- =========================================================
-- Purpose:
-- 1) Enforce one active mapping between auth user and staff record.
-- 2) Keep onboarding/rebinding actions fully auditable.

CREATE TABLE IF NOT EXISTS public.staff_auth_bindings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id TEXT NOT NULL REFERENCES public.staff_directory(id) ON DELETE RESTRICT,
  auth_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  app_role TEXT NOT NULL CHECK (app_role IN ('Owner', 'FH', 'BH')),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  linked_by TEXT NOT NULL,
  linked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  note TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS staff_auth_bindings_staff_active_uq
  ON public.staff_auth_bindings(staff_id) WHERE is_active;
CREATE UNIQUE INDEX IF NOT EXISTS staff_auth_bindings_user_active_uq
  ON public.staff_auth_bindings(auth_user_id) WHERE is_active;
CREATE UNIQUE INDEX IF NOT EXISTS staff_auth_bindings_email_active_uq
  ON public.staff_auth_bindings((lower(email))) WHERE is_active;

CREATE TABLE IF NOT EXISTS public.staff_auth_binding_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  binding_id BIGINT REFERENCES public.staff_auth_bindings(id),
  action TEXT NOT NULL CHECK (action IN ('link', 'relink', 'unlink')),
  staff_id TEXT NOT NULL,
  auth_user_id UUID NOT NULL,
  email TEXT NOT NULL,
  app_role TEXT NOT NULL,
  performed_by TEXT NOT NULL,
  performed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reason TEXT
);

CREATE OR REPLACE FUNCTION public.bind_auth_user_to_staff(
  p_auth_user_id UUID,
  p_staff_id TEXT,
  p_email TEXT,
  p_performed_by TEXT,
  p_reason TEXT DEFAULT NULL
) RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_role TEXT;
  v_binding_id BIGINT;
BEGIN
  SELECT role INTO v_role FROM public.staff_directory WHERE id = p_staff_id;
  IF v_role IS NULL THEN
    RAISE EXCEPTION 'staff_id % does not exist', p_staff_id;
  END IF;

  UPDATE public.staff_auth_bindings
    SET is_active = FALSE
  WHERE is_active
    AND (staff_id = p_staff_id OR auth_user_id = p_auth_user_id OR lower(email) = lower(trim(p_email)));

  INSERT INTO public.staff_auth_bindings(staff_id, auth_user_id, email, app_role, linked_by, note)
  VALUES (p_staff_id, p_auth_user_id, lower(trim(p_email)), v_role, p_performed_by, p_reason)
  RETURNING id INTO v_binding_id;

  INSERT INTO public.staff_auth_binding_audit(binding_id, action, staff_id, auth_user_id, email, app_role, performed_by, reason)
  VALUES (v_binding_id, 'link', p_staff_id, p_auth_user_id, lower(trim(p_email)), v_role, p_performed_by, p_reason);

  RETURN v_binding_id;
END;
$$;

REVOKE ALL ON FUNCTION public.bind_auth_user_to_staff(UUID, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.bind_auth_user_to_staff(UUID, TEXT, TEXT, TEXT, TEXT) TO service_role;

ALTER TABLE public.staff_auth_bindings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_auth_binding_audit ENABLE ROW LEVEL SECURITY;
