-- =========================================================
-- BakeryOS Base Schema Execution Guide
-- =========================================================
-- Files were split to keep each migration script <= 100 lines.
-- Run in this order:
--   1) schema_tables.sql
--   2) schema_seed.sql
--   3) schema_dev_policies.sql   (development only)
--
-- Production:
--   After schema_tables.sql + schema_seed.sql, apply production hardening
--   scripts instead of schema_dev_policies.sql.