-- ==========================================
-- 1. CREATE TABLES
-- ==========================================

-- Table for Menu Items
CREATE TABLE public.menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL
);

-- Table for Staff Directory
CREATE TABLE public.staff_directory (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    can_manage_products BOOLEAN DEFAULT FALSE
);

-- Table for EOD (End of Day) Reports
CREATE TABLE public.eod_reports (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    shift TEXT NOT NULL,
    gross_sales NUMERIC DEFAULT 0,
    promptpay NUMERIC DEFAULT 0,
    card NUMERIC DEFAULT 0,
    expected_cash NUMERIC DEFAULT 0,
    actual_cash NUMERIC DEFAULT 0,
    discrepancy NUMERIC DEFAULT 0,
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table for Pre-Orders / Online Orders
CREATE TABLE public.online_orders (
    id TEXT PRIMARY KEY,
    customer TEXT NOT NULL,
    items JSONB NOT NULL, -- Stores the cart array
    total NUMERIC NOT NULL,
    status TEXT DEFAULT 'pending',
    date TEXT,
    logged_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table for Expenses
CREATE TABLE public.expenses (
    id TEXT PRIMARY KEY,
    date TEXT,
    time TEXT,
    description TEXT,
    qty INTEGER DEFAULT 1,
    unit_price NUMERIC,
    total NUMERIC,
    paid_from TEXT,
    remark TEXT,
    logged_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table for Kitchen Showcase Requests
CREATE TABLE public.showcase_requests (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    time_requested TEXT,
    requested_by TEXT,
    time_delivered TEXT,
    delivered_by TEXT,
    delivered_qty INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 2. INSERT INITIAL MOCK DATA
-- ==========================================

INSERT INTO public.staff_directory (id, name, role, can_manage_products) VALUES
    ('s1', 'Khun Jane', 'FH', false),
    ('s2', 'Khun A', 'BH', false),
    ('s3', 'Khun Boy', 'FH', true),
    ('owner', 'Bakery Owner', 'Owner', true);

INSERT INTO public.menu_items (id, name, price) VALUES
    (1, 'Coconut Cake', 95.0),
    (2, 'Mango Mini', 95.0),
    (3, 'Rich Chocolate', 95.0),
    (4, 'Matcha Raspberry', 95.0),
    (5, 'Applepresso', 120.0);

-- ==========================================
-- 3. DEVELOPMENT SECURITY POLICIES
-- ==========================================
-- NOTE: Because your app uses a mock login without real Supabase Auth,
-- we must temporarily allow all anonymous operations so your app can write data.
-- Replace these with strict Row Level Security (RLS) before going to production!

-- Enable RLS on all tables
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_directory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eod_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.online_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.showcase_requests ENABLE ROW LEVEL SECURITY;

-- Create policies allowing ALL operations (Read/Write/Delete) for everyone
CREATE POLICY "Allow all operations for menu_items" ON public.menu_items FOR ALL USING (true);
CREATE POLICY "Allow all operations for staff" ON public.staff_directory FOR ALL USING (true);
CREATE POLICY "Allow all operations for eod" ON public.eod_reports FOR ALL USING (true);
CREATE POLICY "Allow all operations for orders" ON public.online_orders FOR ALL USING (true);
CREATE POLICY "Allow all operations for expenses" ON public.expenses FOR ALL USING (true);
CREATE POLICY "Allow all operations for showcase" ON public.showcase_requests FOR ALL USING (true);