-- ==========================================
-- BakeryOS Schema: Core Tables
-- ==========================================

CREATE TABLE public.menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL
);

CREATE TABLE public.staff_directory (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    can_manage_products BOOLEAN DEFAULT FALSE
);

CREATE TABLE public.eod_reports (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    shift TEXT NOT NULL,
    gross_sales NUMERIC DEFAULT 0,
    promptpay NUMERIC DEFAULT 0,
    card NUMERIC DEFAULT 0,
    expected_cash NUMERIC DEFAULT 0,
    actual_cash NUMERIC DEFAULT 0,
    discrepancy NUMERIC DEFAULT 0,
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.online_orders (
    id TEXT PRIMARY KEY,
    customer TEXT NOT NULL,
    items JSONB NOT NULL,
    total NUMERIC NOT NULL,
    status TEXT DEFAULT 'pending',
    date TEXT,
    logged_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.expenses (
    id TEXT PRIMARY KEY,
    date TEXT,
    time TEXT,
    description TEXT,
    qty INTEGER DEFAULT 1,
    unit_price NUMERIC,
    total NUMERIC,
    paid_from TEXT,
    remark TEXT,
    logged_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.showcase_requests (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    time_requested TEXT,
    requested_by TEXT,
    time_delivered TEXT,
    delivered_by TEXT,
    delivered_qty INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
